FROM node:lts-alpine

WORKDIR /home/tailwind/api

ENV NODE_ENV=production

COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile

COPY . .
RUN yarn build:api

ENTRYPOINT ["node", "dist/server.js"]