FROM node:lts-alpine

WORKDIR /home/tailwind/client

COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile

COPY . .
RUN yarn build:client

FROM nginx:alpine
COPY --from=0 /home/tailwind/client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /home/tailwind/client/build /usr/share/nginx/html